name: deploy
on: push
jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: notify about commit on telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ⚙ <a href="https://github.com/cloudr-app/cloudr/commit/${{ github.event.after }}">new commit</a> by ${{ github.event.pusher.name }}.
            ${{ github.event.head_commit.message }}

  sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
