name: telegram message
on: push
jobs:
  telegram:
    name: notify about commit on telegram
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ⚙ <a href="https://github.com/cloudr-app/cloudr/commit/${{ github.event.after }}">new commit</a> by ${{ github.event.pusher.name }}.
            ${{ github.event.head_commit.message }}
